name: Build void packages

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      max-parallel: 1
      matrix:
        arch: [x86_64]
        # arch: [x86_64, x86_64-musl]
    runs-on: ubuntu-latest
    env:
      XBPS_ALLOW_RESTRICTED: "yes"
      XBPS_PASSPHRASE: ${{ secrets.SIGN_PASS }}
      XBPS_TARGET_ARCH: ${{ matrix.arch }}
      REPO_OWNER: "${{ github.repository_owner }}"
      REPO_NAME: "${{ github.event.repository.name }}"

    steps:
      - name: checkout ${{ env.REPO_NAME }}
        uses: actions/checkout@v4
        with:
          ref: main
          path: ${{ env.REPO_NAME }}

      - name: checkout void-packages
        uses: actions/checkout@v4
        with:
          repository: void-linux/void-packages
          ref: master
          path: void-packages

      - name: copy
        run: |
          cat ${{ env.REPO_NAME }}/common/shlibs >> void-packages/common/shlibs
          cp -rv ${{ env.REPO_NAME }}/srcpkgs/* void-packages/srcpkgs

      - name: prepare xbps-static
        run: |
          mkdir -p /opt/xbps
          curl -LO http://repo-default.voidlinux.org/static/xbps-static-latest.x86_64-musl.tar.xz
          tar xvf xbps-static-latest.x86_64-musl.tar.xz -C /opt/xbps
          rm xbps-static-latest.x86_64-musl.tar.xz

      # - name: free space
      #   run: |
      #     sudo rm -rf /usr/share/dotnet
      #     sudo rm -rf /usr/local/lib/android
      #     sudo rm -rf /opt/ghc
      #     sudo rm -rf /opt/hostedtoolcache/CodeQL

      - name: set path
        run: |
          echo "/opt/xbps/usr/bin/" >> $GITHUB_PATH

      - name: setup binray bootstrap
        working-directory: void-packages
        run: |
          ./xbps-src -m masterdir-${{ matrix.arch }} -A ${{ matrix.arch }} binary-bootstrap

      - name: Build Swayosd
        working-directory: void-packages
        run: |
         ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} swayosd

      - name: Build tomlplusplus
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} tomlplusplus

      - name: Build sdbus-cpp
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} sdbus-cpp

      - name: Build hyprutils
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprutils

      - name: Build hyprlang
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprlang

      - name: Build hyprland
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprland

      - name: Build hyprland-protocols
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprland-protocols

      - name: Build xdg-desktop-portal-hyprland
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} xdg-desktop-portal-hyprland

      - name: Build hyprcursor
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprcursor

      - name: Build hyprwayland-scanner
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprwayland-scanner

      - name: Build hypridle
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hypridle

      - name: Build hyprlock
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprlock

      - name: Build hyprpaper
        working-directory: void-packages
        run: |
          ./xbps-src pkg -j$(nproc) -m masterdir-${{ matrix.arch }} hyprpaper

      - name: sign
        working-directory: void-packages/hostdir/binpkgs/
        run: |
          xbps-rindex -r $PWD
          xbps-rindex -s --signedby "${{ env.REPO_NAME }}-github-action" --privkey <(printf '%s' "${{ secrets.PRIV_KEY }}") $PWD
          xbps-rindex -S --privkey <(printf '%s' "${{ secrets.PRIV_KEY }}") $PWD/*.xbps
          xbps-rindex -c $PWD
          ls -la

      # - name: checksum
      #   working-directory: void-packages/hostdir/binpkgs/
      #   run: |
      #     sha256sum $(echo librewolf-*.${{ matrix.arch }}.xbps) | tee $(echo librewolf-*.${{ matrix.arch }}.xbps).sha256sum
      #     sha512sum $(echo librewolf-*.${{ matrix.arch }}.xbps) | tee $(echo librewolf-*.${{ matrix.arch }}.xbps).sha512sum

      - name: checksum
        working-directory: void-packages/hostdir/binpkgs/
        run: |
          for file in *.xbps; do
            sha256sum "$file" | cut -d ' ' -f 1 > "${file}.sha256sum"
            sha512sum "$file" | cut -d ' ' -f 1 > "${file}.sha512sum"
          done

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            void-packages/hostdir/binpkgs/*.xbps
            void-packages/hostdir/binpkgs/*.sha256sum
            void-packages/hostdir/binpkgs/*.sha512sum
            void-packages/hostdir/binpkgs/*.sig2
            void-packages/hostdir/binpkgs/*repodata
